apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend-deployment
spec:
  replicas: 2
  selector:
    matchLabels:
      app: backend
  template:
    metadata:
      labels:
        app: backend
    spec:
      containers:
        - name: backend
          image: 920726643262.dkr.ecr.us-east-1.amazonaws.com/product-management-backend-app:latest
          ports:
            - containerPort: 8080
